approve_by_comment: true
approve_regex: ^((A|a)pproved|:shipit:( )?|:\+1:( )?)$
reject_regex: ^((R|r)ejected|:shipit:( )?|:-1:( )?)$
reset_on_push: false
author_approval: ignored
reviewers:
    -
        name: release-ops
        required: 1
        members:
            - etremblay
            - jbreton
            - vlemieux
            - nvanheuverzwijn
    -
        name: peers
        required: 1
        members:
            - etremblay
            - jbreton
            - vlemieux
            - abrassard
            - AlexPoirier1
            - antoinedeschenes
            - glorquet
            - grochat614
            - LeSDT
            - mdemers-kronos
            - nvanheuverzwijn
            - ogermain-kronos
            - plpaquin
            - fredjoncas
